import datetime

default_soil = {'CONTAB': [0.0,
                           1.033,
                           1.0,
                           -0.824,
                           1.3,
                           -1.155,
                           1.491,
                           -1.398,
                           1.7,
                           -1.523,
                           2.0,
                           -1.959,
                           2.4,
                           -2.495,
                           2.7,
                           -2.886,
                           3.0,
                           -3.276,
                           3.4,
                           -3.77,
                           3.7,
                           -4.131,
                           4.0,
                           -4.481,
                           4.204,
                           -4.745],
                'CRAIRC': 0.05,
                'DEFLIM': -0.3,
                'K0': 10.789,
                'KSUB': 0.37,
                'RDMSOL': 120.0,
                'SM0': 0.57,
                'SMFCF': 0.46,
                'SMTAB': [-1.0,
                          0.57,
                          1.0,
                          0.533,
                          1.3,
                          0.524,
                          1.491,
                          0.515,
                          2.0,
                          0.486,
                          2.4,
                          0.451,
                          2.7,
                          0.42,
                          3.4,
                          0.35,
                          4.204,
                          0.3,
                          6.0,
                          0.27],
                'SMW': 0.3,
                'SOLNAM': 'EC4-fine',
                'SOPE': 0.55,
                'SPADS': 0.05,
                'SPASS': 0.1,
                'SPODS': 0.025,
                'SPOSS': 0.04,
                'SM': 0.3}

default_site = {'BG_K_SUPPLY': 0.091,
                'BG_N_SUPPLY': 0.091,
                'BG_P_SUPPLY': 0.091,
                'IFUNRN': 0,
                'KSOILBASE': 10.0,
                'KSOILBASE_FR': 0.025,
                'NOTINF': 0.0,
                'NSOILBASE': 10.0,
                'NSOILBASE_FR': 0.025,
                'PSOILBASE': 10.0,
                'PSOILBASE_FR': 0.025,
                'SMLIM': 0.3,
                'SSI': 0.0,
                'SSMAX': 0.0,
                'WAV': 50}

default_crop = {'AMAXTB': [0.0, 35.83, 1.0, 35.83, 1.3, 35.83, 2.0, 4.48],
                'CFET': 1.0,
                'CO2': 720.0,
                'CO2AMAXTB': [40.0, 0.0, 360.0, 1.0, 720.0, 1.35, 1000.0, 1.5, 2000.0, 1.5],
                'CO2EFFTB': [40.0, 0.0, 360.0, 1.0, 720.0, 1.11, 1000.0, 1.11, 2000.0, 1.11],
                'CO2TRATB': [40.0, 0.0, 360.0, 1.0, 720.0, 0.9, 1000.0, 0.9, 2000.0, 0.9],
                'CRPNAM': 'Winter wheat 102, Ireland, N-U.K., Netherlands, N-Germany',
                'CVL': 0.685,
                'CVO': 0.709,
                'CVR': 0.694,
                'CVS': 0.662,
                'DEPNR': 4.5,
                'DLC': -99.0,
                'DLO': -99.0,
                'DTSMTB': [0.0, 0.0, 30.0, 30.0, 45.0, 30.0],
                'DVSDLT': 1.0,
                'DVSDR': 1.0,
                'DVSEND': 2.0,
                'DVSI': 0.0,
                'DVS_NPK_STOP': 1.3,
                'DVS_NPK_TRANSL': 0.8,
                'EFFTB': [0.0, 0.45, 40.0, 0.45],
                'FLTB': [0.0,
                         0.65,
                         0.1,
                         0.65,
                         0.25,
                         0.7,
                         0.5,
                         0.5,
                         0.646,
                         0.3,
                         0.95,
                         0.0,
                         2.0,
                         0.0],
                'FOTB': [0.0, 0.0, 0.95, 0.0, 1.0, 1.0, 2.0, 1.0],
                'FRTB': [0.0,
                         0.5,
                         0.1,
                         0.5,
                         0.2,
                         0.4,
                         0.35,
                         0.22,
                         0.4,
                         0.17,
                         0.5,
                         0.13,
                         0.7,
                         0.07,
                         0.9,
                         0.03,
                         1.2,
                         0.0,
                         2.0,
                         0.0],
                'FSTB': [0.0,
                         0.35,
                         0.1,
                         0.35,
                         0.25,
                         0.3,
                         0.5,
                         0.5,
                         0.646,
                         0.7,
                         0.95,
                         1.0,
                         1.0,
                         0.0,
                         2.0,
                         0.0],
                'IAIRDU': 0,
                'IDSL': 0,
                'IOX': 0,
                'KCRIT_FR': 1.0,
                'KDIFTB': [0.0, 0.6, 2.0, 0.6],
                'KMAXLV_TB': [0.0,
                              0.12,
                              0.4,
                              0.08,
                              0.7,
                              0.06,
                              1.0,
                              0.04,
                              2.0,
                              0.028,
                              2.1,
                              0.028],
                'KMAXRT_FR': 0.5,
                'KMAXSO': 0.0048,
                'KMAXST_FR': 0.5,
                'KRESIDLV': 0.009,
                'KRESIDRT': 0.005,
                'KRESIDST': 0.005,
                'LAIEM': 0.1365,
                'NCRIT_FR': 1.0,
                'NFIX_FR': 0.0,
                'NLAI_NPK': 1.0,
                'NLUE_NPK': 1.1,
                'NMAXLV_TB': [0.0,
                              0.06,
                              0.4,
                              0.04,
                              0.7,
                              0.03,
                              1.0,
                              0.02,
                              2.0,
                              0.014,
                              2.1,
                              0.014],
                'NMAXRT_FR': 0.5,
                'NMAXSO': 0.0176,
                'NMAXST_FR': 0.5,
                'NPART': 1.0,
                'NPK_TRANSLRT_FR': 0.15,
                'NRESIDLV': 0.004,
                'NRESIDRT': 0.002,
                'NRESIDST': 0.002,
                'NSLA_NPK': 0.5,
                'PCRIT_FR': 1.0,
                'PERDL': 0.03,
                'PMAXLV_TB': [0.0,
                              0.011,
                              0.4,
                              0.008,
                              0.7,
                              0.006,
                              1.0,
                              0.004,
                              2.0,
                              0.0027,
                              2.1,
                              0.0027],
                'PMAXRT_FR': 0.5,
                'PMAXSO': 0.0026,
                'PMAXST_FR': 0.5,
                'PRESIDLV': 0.0005,
                'PRESIDRT': 0.0003,
                'PRESIDST': 0.0003,
                'Q10': 2.0,
                'RDI': 10.0,
                'RDMCR': 125.0,
                'RDRLTB': [-10.0, 0.0, 10.0, 0.02, 15.0, 0.03, 30.0, 0.05, 50.0, 0.09],
                'RDRLV_NPK': 0.05,
                'RDRRTB': [0.0, 0.0, 1.5, 0.0, 1.5001, 0.02, 2.0, 0.02],
                'RDRSTB': [0.0, 0.0, 1.5, 0.0, 1.5001, 0.02, 2.0, 0.02],
                'RFSETB': [0.0, 1.0, 2.0, 1.0],
                'RGRLAI': 0.00817,
                'RML': 0.03,
                'RMO': 0.01,
                'RMR': 0.015,
                'RMS': 0.015,
                'RRI': 1.2,
                'SLATB': [0.0, 0.00212, 0.5, 0.00212, 2.0, 0.00212],
                'SPA': 0.0,
                'SPAN': 31.3,
                'SSATB': [0.0, 0.0, 2.0, 0.0],
                'TBASE': 0.0,
                'TBASEM': -10.0,
                'TCKT': 10.0,
                'TCNT': 10.0,
                'TCPT': 10.0,
                'TDWI': 210.0,
                'TEFFMX': 30.0,
                'TMNFTB': [0.0, 0.0, 3.0, 1.0],
                'TMPFTB': [0.0, 0.01, 10.0, 0.6, 15.0, 1.0, 25.0, 1.0, 35.0, 0.0],
                'TSUM1': 1050.0,
                'TSUM2': 1000.0,
                'TSUMEM': 0.0}

default_amgt = [{datetime.date(2014, 9, 1): {'CropCalendar': {'crop_end_date': datetime.date(2015, 7, 1),
                                                              'crop_end_type': 'harvest',
                                                              'crop_name': 'wheat',
                                                              'crop_start_date': datetime.date(2014, 10, 1),
                                                              'crop_start_type': 'sowing',
                                                              'max_duration': 330,
                                                              'variety_name': 'winter-wheat'},
                                             'StateEvents': None,
                                             'TimedEvents': [{'comment': 'All fertilizer amounts in kg/ha',
                                                              'event_signal': 'apply_npk',
                                                              'events_table': [
                                                                {datetime.date(2014, 9, 10): {'K_amount': 20.0,
                                                                                              'K_recovery': 0.7,
                                                                                              'N_amount': 0.0,
                                                                                              'N_recovery': 0.7,
                                                                                              'P_amount': 40.0,
                                                                                              'P_recovery': 0.7}},
                                                                {datetime.date(2014, 12, 5): {'K_amount': 20.0,
                                                                                              'K_recovery': 0.7,
                                                                                              'N_amount': 0.0,
                                                                                              'N_recovery': 0.7,
                                                                                              'P_amount': 10.0,
                                                                                              'P_recovery': 0.7}}],
                                                              'name': 'Timed N/P/K application table'}]}}]
